<template>
  <div class="intro-password">
    <main>
      <h2>Secure your Node with a unique password.</h2>
      <p>12+ characters. We highly recommend using a password manager.</p>

      <!-- Todo: Only initialize error handling on submit -->
      <!-- Todo: Display error message generated by VeeValidate -->
      <ValidationProvider ref="password" v-slot="{ errors }" rules="required|min:12">
        <InputField v-model="password" label="Node Password" name="Node Password" type="password" :error="Boolean(errors.length)" />
      </ValidationProvider>
    </main>

    <footer>
      <a class="button is-primary" @click="submit()">
        Submit
      </a>
    </footer>
  </div>
</template>

<script>
  export default {
    data() {
      return {
        seedPhrase: [],
        password: '',
      }
    },

    mounted() {
      // Get seed from the route parameters, since variables are cleared between pages
      if(this.$route.params.seedPhrase !== undefined
          && Array.isArray(this.$route.params.seedPhrase)
          && this.$route.params.seedPhrase.length === 24) {
        this.seedPhrase = this.$route.params.seedPhrase;
      }
    },

    methods: {
      async submit() {
        const validator = await this.$refs.password.validate();

        if(validator.valid) {
          this.initWallet();
        }
      },

      async initWallet() {

      },

      async register() {
        try {
          const data = {
            password: this.setup.password,
          };

          await this.$axios.post(`${this.$env.API_MANAGER}/v1/accounts/register`, data);
          this.$router.push({path: '/intro/got-it'});
        } catch (error) {
          // Todo: Output this error in a more user friendly way
          console.error(`Failed to Register - ${error.response.data}`);
        }
      }
    },
  }
</script>

<style lang="scss">
  .intro-password {
    main p {
      margin-top: -0.5em;
    }

    .input-wrap {
      margin-top: 3em;
      width: 500px;
    }
  }
</style>
